### ISSUE TITLE
[TEST] ensuring batch analysis works

### ISSUE THREAD

**Issue by pr4deepr** [pr4deepr/GutAnalysisToolbox#21]
@mattyrowey 

Could you ensure batch analysis option works and the documentation is clear?

You'll have to update GAT

Documentation is here:

https://gut-analysis-toolbox.gitbook.io/docs/2.-cell-counts-and-ganglia-analysis/batch-analysis

**Comment by mattyrowey** [comment]
Yes, I can test this shortly

**Comment by mattyrowey** [comment]
@pr4deepr 

I've tested the batch analysis multiple times using the starting code provided in the documentation and it has worked without any errors for me. All the results and images seem to be saving correctly as well.

In terms of the documentation, I noticed two things.
There is a typo in the documentation (see image below)

It is unclear how to "download this as a macro". I used the copy button but I wasn't sure if there was supposed to be a specific download link.
 
![Batch Analysis Documentation Typo](https://github.com/pr4deepr/GutAnalysisToolbox/assets/167947170/81cffa67-73b0-4c27-8875-261ff6868bf1)
![How to Download](https://github.com/pr4deepr/GutAnalysisToolbox/assets/167947170/2064c4a2-e5cc-4ef9-a528-f6edafde2845)

**Comment by pr4deepr** [comment]
Thanks Matt. Super helpful. 
I've added a link, could you check and let me know if the instructions are clear?

**Comment by mattyrowey** [comment]
The instructions are reasonably clear. I think it is still too complex for a user with no background in Fiji image analysis however I assume this is not pitched for them anyway?

A few suggestions to improve the clarity:

**Comment by mattyrowey** [comment]
The instructions are reasonably clear. I think it is still too complex for a user with no background in Fiji image analysis however I assume this is not pitched for them anyway?

My suggestions to improve the clarity:
![image](https://github.com/pr4deepr/GutAnalysisToolbox/assets/167947170/769d5d7c-2771-466b-8f8e-080be4098a92)
Update to:
GAT can now be called from within a macro, making it possible to integrate it into your Fiji analysis workflows. 

![image](https://github.com/pr4deepr/GutAnalysisToolbox/assets/167947170/fa335021-4a2e-4c07-93e4-822f0153739b)
Update to:
This is possible by using script parameters within an ImageJ macro. This will allow GAT to run without any user input. For this to work, you will first need to define specific arguments within the ImageJ macro.

![image](https://github.com/pr4deepr/GutAnalysisToolbox/assets/167947170/d36a299b-7f37-44e0-9686-3f95e8e5ef80)
Update to:
There are two sets of arguments that must be defined.

![image](https://github.com/pr4deepr/GutAnalysisToolbox/assets/167947170/f502cdc9-f8d5-4732-a437-4521f9cbee31)
Update to:
Expansion or neuron dilation value (default = 6.5 µm)

![image](https://github.com/pr4deepr/GutAnalysisToolbox/assets/167947170/be55552f-4b47-4073-9ad0-406640af92d0)
Update to:
Scaling factor (default = 1)

![image](https://github.com/pr4deepr/GutAnalysisToolbox/assets/167947170/2ff60c62-b47a-4120-92c6-ac510812fd7a)
Update to:
A complete example of an ImageJ macro is provided below. Please note that 'true' or 'false' will need to be passed as a string and not as a boolean.

**Comment by pr4deepr** [comment]
Thanks Matt! Looks great!

> This is possible by using script parameters within an ImageJ macro. This will allow GAT to run without any user input. For this to work, you will first need to define specific arguments within the ImageJ macro.

What I meant with the first sentences is, the functionality to call GAT from another macro is due to our use of script parameters in GAT.

Let me know if the edits look good

**Comment by mattyrowey** [comment]
Ahh I see!

Yea I just read through it, the edits looks good.
