### ISSUE TITLE
Detecting # of nuclei per ganglia 

### ISSUE THREAD

**Issue by haleydeselle** [pr4deepr/GutAnalysisToolbox#9]
When using the GAT feature in Fiji, it allows me to count the number of neurons in the image I upload, but it will not count the number of neurons per ganglia. After it counts the neurons, and I okay what the program has labeled as a neuron, it gives me a Macro Error saying "Stack required in line 81 (called from line 64), Stack . <setChannel> ( ganglia_channel ) ;". When I click the "OK" button on this error. it displays a box that says "Ganglia image not a binary image". I am not really sure what any of this means, and my knowledge on this software is pretty limited. Is this something you are able to assist me on?

**Comment by pr4deepr** [comment]
Hi @haleydeselle 
 Thanks for using GAT.
Did you follow the instructions here?
https://github.com/pr4deepr/GutAnalysisToolbox/wiki/2.-Cell-Count-Analysis#segmenting-ganglia

Essentially, we need another channel for determining the ganglia. It could be a marker for glial or neuronal fibres. Do you have that or do you only have Hu?

**Comment by pr4deepr** [comment]
Also, you said "nuclei" in the title. 
What market are you using for neurons?
Could you share a sample image ?

**Comment by haleydeselle** [comment]
I made a mistake in the title, I meant neuron. We use Huc/D for marking neurons, and we use TUJ for marking neuronal fibers. I followed the directions from the video for selecting the channel for marking ganglia, etc.  At this point, I've separated the Z-stack images into separate channels, Hu, TUJ, and MHCII (for macrophages) when initially opening the image in Fiji. Then when using GAT, I only select the channels for Hu and TUJ for the neurons and neuronal fibers respectively. Maybe my problem is that I need to create a composite image that has both Hu and TUJ only, then open that image in FIJI and go from there?

**Comment by pr4deepr** [comment]
Ahh, yes you don't need to separate any of the channels. Using a composite image is the way to go.  I'll make this clear in the documentation. The channel numbers are based on the order they are within the composite image.

In addition to tif files, you can open czi files from Zeiss microscope or lif files from Leica directly within GAT.


Question, how good is the neuronal segmentation? Does it work well? I'm curious to see how the ganglia segmentation works out too. 
If GAT doesn't segment your data well , I'm keen to get some training data to improve the models in the future. Details here: https://github.com/pr4deepr/GutAnalysisToolbox/wiki/Contributing-to-GAT#create-training-data-as-you-analyze

**Comment by haleydeselle** [comment]
I apologize for the delayed reply! The neuronal segmentation works beautifully actually.  I feel that it is accurate in the neuronal counting. I am now trying with the composite image, and it is giving me this error message "The source stacks must have the same number of images. In line 91 (called from line 64). Run ("Merge Channels..." , "c1=ganglia_ch c2=cells_ch create" <)> ; " After I hit "OK", it tells me again that "Ganglia image not a binary image"

I am not entirely sure what this message means. I created a composite image by creating a "Z project" of the Z stack files I made with the confocal scope for each HuC/D and TUJ, then merged the two to create one composite image. Each of the "Z projects" should have compressed the same number of images/stacks into one plane. I will double check that and get back to you.

**Comment by pr4deepr** [comment]
Hi
  Could you try the workflow with the sample images in this repository?
Can you download this image:
https://github.com/pr4deepr/GutAnalysisToolbox/blob/main/Sample%20Images/181107_ms_distal_colon_nNOS_GFAP_Hu_40X.tif
Use nNOS or GFAP channel, i.e., channel 1 or channel 2 for the ganglia and let me know if you get the same error? 

If you do get an error, it could be something to do with your GAT installation maybe. If so, can you update GAT? `Help ->Update`. 

Happy to have a quick chat. You can email me at: pradeep.rajasekhar@gmail.com and we can setup a time.

Cheers
Pradeep

**Comment by pr4deepr** [comment]
Resolved:
Needed to use composite images when running analysis (updated documentation to reflect this)

Feel free to reopen this if needed
